language: python
python:
    - "3.6"
cache: pip
install: 
- pip install -r requirements.txt
- pip install coveralls
- pip install coverage
script: 
- coverage run -m unittest tests
- coverage report -m
after_success:
  - coveralls
